### ISSUE TITLE
Having trouble dumping depth from scene0207_02: zlib.error: Error -3 while decompressing data: invalid distance cod

### ISSUE THREAD

**Issue by HaFred** [ScanNet/ScanNet#100]
I am using https://github.com/ScanNet/ScanNet/blob/1cc5149d30d248b776039c76ae8864e63df18831/SensReader/python/reader.py to read sens files. But I ran into the following errors for `scene0207_02` only, while **other scenes are fine to read and dump data**. 
```
Traceback (most recent call last):
  File "./SensReader/python/reader.py", line 79, in <module>
    main()
  File "./SensReader/python/reader.py", line 35, in main
    sd.export_depth_images(os.path.join(opt.output_path, 'depth'))
  File "/home/zhongad/3D_workspace/dataset/ScanNet/SensReader/python/SensorData.py", line 78, in export_depth_images
    depth_data = self.frames[f].decompress_depth(self.depth_compression_type)
  File "/home/zhongad/3D_workspace/dataset/ScanNet/SensReader/python/SensorData.py", line 26, in decompress_depth
    return self.decompress_depth_zlib()
  File "/home/zhongad/3D_workspace/dataset/ScanNet/SensReader/python/SensorData.py", line 31, in decompress_depth_zlib
    return zlib.decompress(self.depth_data)
zlib.error: Error -3 while decompressing data: invalid distance code
```
Does anyone know how to solve this? P.S. I downloaded the dataset in Nov 2021.

**Comment by 87Donghyung** [comment]
Do you solve this problem?? I am having the same problem as you

**Comment by HaFred** [comment]
Sometimes the download may be corrupted. This issue is due to the incompleted src files. For me I just redownload this particular scene and ran the sens reader and it works fine now.

**Comment by 87Donghyung** [comment]
Really Thank you for your reply
