### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by novasky0709** [ScanNet/ScanNet#107]
Hi, thanks for the awesome work !
when I download the dataset, I got the following error:
```
python download-scannet.py -o .
By pressing any key to continue you confirm that you have agreed to the ScanNet terms of use as described at:
http://kaldir.vc.in.tum.de/scannet/ScanNet_TOS.pdf
***
Press any key to continue, or CTRL-C to exit.
Traceback (most recent call last):
  File "download-scannet.py", line 184, in <module>
    if __name__ == "__main__": main()
  File "download-scannet.py", line 118, in main
    release_scans = get_release_scans(release_file)
  File "download-scannet.py", line 27, in get_release_scans
    scan_lines = urllib.request.urlopen(release_file)
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/slam/miniconda3/envs/pointnerf/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Could you please give me any suggestion about that? Thanks. Note that I had used the same command to download several rooms successfully.

**Comment by novasky0709** [comment]
Hi, thanks for the awesome work!
when I was downloading the dataset use the following command
