### ISSUE TITLE
Getting an error when trying to download the entire dataset

### ISSUE THREAD

**Issue by DarKayserLeo** [ScanNet/ScanNet#122]
Hi I was downloading the entire dataset, at this point I spent weeks due to my internet connection and downloaded almost 2TB of dataset. It looks like it will never end! and I starting to worry about that. Sadly today the download script stopped working and is throwing this error:

```
Downloaded scan scene0802_00
Downloading ScanNet v2 scan scene0803_00 ...
WARNING: skipping download of existing file G:/scans_test\scene0803_00/scene0803_00.sens
WARNING: skipping download of existing file G:/scans_test\scene0803_00/scene0803_00.txt
WARNING: skipping download of existing file G:/scans_test\scene0803_00/scene0803_00_vh_clean.ply
WARNING: skipping download of existing file G:/scans_test\scene0803_00/scene0803_00_vh_clean_2.ply
Downloaded scan scene0803_00
Downloading ScanNet v2 scan scene0804_00 ...
WARNING: skipping download of existing file G:/scans_test\scene0804_00/scene0804_00.sens
WARNING: skipping download of existing file G:/scans_test\scene0804_00/scene0804_00.txt
WARNING: skipping download of existing file G:/scans_test\scene0804_00/scene0804_00_vh_clean.ply
WARNING: skipping download of existing file G:/scans_test\scene0804_00/scene0804_00_vh_clean_2.ply
Downloaded scan scene0804_00
Downloading ScanNet v2 scan scene0805_00 ...
WARNING: skipping download of existing file G:/scans_test\scene0805_00/scene0805_00.sens
WARNING: skipping download of existing file G:/scans_test\scene0805_00/scene0805_00.txt
WARNING: skipping download of existing file G:/scans_test\scene0805_00/scene0805_00_vh_clean.ply
WARNING: skipping download of existing file G:/scans_test\scene0805_00/scene0805_00_vh_clean_2.ply
Downloaded scan scene0805_00
Downloading ScanNet v2 scan scene0806_00 ...
WARNING: skipping download of existing file G:/scans_test\scene0806_00/scene0806_00.sens
WARNING: skipping download of existing file G:/scans_test\scene0806_00/scene0806_00.txt
WARNING: skipping download of existing file G:/scans_test\scene0806_00/scene0806_00_vh_clean.ply
WARNING: skipping download of existing file G:/scans_test\scene0806_00/scene0806_00_vh_clean_2.ply
Downloaded scan scene0806_00
Downloaded ScanNet v2 release.
        http://kaldir.vc.in.tum.de/scannet/v2/tasks\scannet_frames_test.zip > G:/tasks\scannet_frames_test.zip
Traceback (most recent call last):
  File "C:\Users\DarKayserLeo\Documents\Projects\Tesis\download-scannet.py", line 237, in <module>
    if __name__ == "__main__": main()
  File "C:\Users\DarKayserLeo\Documents\Projects\Tesis\download-scannet.py", line 232, in main
    download_file(os.path.join(BASE_URL, RELEASE_TASKS, TEST_FRAMES_FILE[0]), os.path.join(out_dir_tasks, TEST_FRAMES_FILE[0]))
  File "C:\Users\DarKayserLeo\Documents\Projects\Tesis\download-scannet.py", line 61, in download_file
    urllib.request.urlretrieve(url, out_file_tmp)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\DarKayserLeo\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Please! I need help! I feel like I wasted so much time and I need this dataset for another project I need to run and test ASAP.

Also can you tell me which is the whole size of the entire dataset? I tought it was only 1.3T but as I said I almost downloaded 2TB and my external hard drive will explode very soon.

**Comment by DarKayserLeo** [comment]
Please I need to solve this

**Comment by glennliu** [comment]
I can download parts of files in some of the scans.
For ```scene_0733_00``` from test scans, I can download most of its files except ```_vh_clean_2.0.010000.segs.json ```. 
For ```scene_0144_00``` from validation scans, I can download most of its files except ```.sens```. 
When a download is failed, it shows
```terminal
HTTP request sent, awaiting response... 404 Not Found
2022-10-28 20:57:02 ERROR 404: Not Found.
```

The link worked well for me and I recently meets the problem. Are you able to download a specific scan or file?

**Comment by DarKayserLeo** [comment]
> I can download parts of files in some of the scans. For `scene_0733_00` from test scans, I can download most of its files except `_vh_clean_2.0.010000.segs.json `. For `scene_0144_00` from validation scans, I can download most of its files except `.sens`. When a download is failed, it shows
> 
> ```
> HTTP request sent, awaiting response... 404 Not Found
> 2022-10-28 20:57:02 ERROR 404: Not Found.
> ```
> 
> The link worked well for me and I recently meets the problem. Are you able to download a specific scan or file?

Hi I'm using this command to download everything:

```
python download-scannet.py -o G:/
```

However it keeps returning the same error I share above when attemps to download

I did not test trying to download a specific scan. Let me try

**Comment by DarKayserLeo** [comment]
And that's it. Finally is over. 

![image](https://user-images.githubusercontent.com/116125432/198646862-170d81c7-8faa-47ff-adc8-c6208bcd168b.png)
