### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by mipa23** [ScanNet/ScanNet#151]
I encountered an error while attempting to download the Scannet dataset using the script "download-scannet.py." Specifically, the error occurred during the download of the file "scannet_frames_test.zip" from the URL "http://kaldir.vc.in.tum.de/scannet/v2/tasks/scannet_frames_test.zip".

The error message is as follows:

```
Downloaded scan scene0806_00
Downloaded ScanNet v2 release.
http://kaldir.vc.in.tum.de/scannet/v2/tasks\scannet_frames_test.zip > F:/Scannet-Dataset\tasks\scannet_frames_test.zip
Traceback (most recent call last):
  File "download-scannet.py", line 240, in <module>
    if __name__ == "__main__": main()
  File "download-scannet.py", line 235, in main
    download_file(os.path.join(BASE_URL, RELEASE_TASKS, TEST_FRAMES_FILE[0]), os.path.join(out_dir_tasks, TEST_FRAMES_FILE[0]))
  File "download-scannet.py", line 61, in download_file
    urllib.request.urlretrieve(url, out_file_tmp)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\<your_username>\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```
It seems that the URL for "scannet_frames_test.zip" is returning a "Not Found" error (HTTP 404). Could you please investigate the issue 

same happens for the following zip files: limited-reconstruction-scenes.zip ....

Thank you for your attention to this matter.

**Comment by LinLin1031** [comment]
May I ask if you've solved it? I also encountered this problem. @mipa23

**Comment by Berta911** [comment]
Any solution now? I got the same problem as well.
