### ISSUE TITLE
UnicodeDecodeError  while downloading Scannet dataset

### ISSUE THREAD

**Issue by Ocean23333** [ScanNet/ScanNet#156]
Hello, I get a problem while downloading the Scannet datset with no idea of solving.
I executed the download script and  received the following return:
`python download_scannet.py -o data
By pressing any key to continue you confirm that you have agreed to the ScanNet terms of use as described at:
http://kaldir.vc.in.tum.de/scannet/ScanNet_TOS.pdf
***
Press any key to continue, or CTRL-C to exit.

Traceback (most recent call last):
  File "download_scannet.py", line 204, in <module>
    if __name__ == "__main__": main()
  File "download_scannet.py", line 135, in main
    release_scans = get_release_scans(release_file)
  File "download_scannet.py", line 34, in get_release_scans
    scan_id = scan_line.decode('utf8').rstrip('\n')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 7: invalid continuation byte
`
Cloud you tell me what should I do?
Thank you for your attention to this matter.

**Comment by kaguramena** [comment]
Same problem, have you sovled it?
